language: node_js
install: 
  - git clone --depth=50 --branch=master https://github.com/teamcodebusters/more-colorful-logger.git teamcodebusters/more-colorful-logger
  - cd teamcodebusters/more-colorful-logger
  - npm install


script:
  - npm pretest
  - npm test